Add Junit Tests
AY1920S2-CS2103T-W17-3/main pull request #125
Opened 2020-03-14 06:55 UTC by joshlay96

Added JUnit Test for FixedCosts, Packing List, and Transport Booking.

2020-03-14 07:05 UTC, joshlay96 commented
Will Fix codacy issues together when other aspects of model is complete.

2020-03-14 07:47 UTC, joshlay96 commented
Please look at the changes and approve. Intention is to use this as a template while model is still being updated

2020-03-14 19:04 UTC, zenatrick requested changes
All test looks good, can merge after the mentioned issues are resolved. (Don't need to change the regex issue yet.)

You can try the following: go to file changed and click add suggestions to batch for all my suggestions and make a commit. Quite convenient and no need to do these small edits in IntelliJ.

2020-03-14 19:04 UTC, zenatrick commented on src/main/java/seedu/address/model/packinglistitem/UniquePackingList.java
> +    public void setPackingLists(UniquePackingList replacement) {
`setPackingList` already means multiple items `setPackingLists` means multiple lists which isn't the intention here


**Suggestions:**
Either (preferred since the above method is `setItem()`)
```suggestion
    public void setItems(UniquePackingList replacement) {
```
Or
```suggestion
    public void setPackingList(UniquePackingList replacement) {
```

2020-03-14 19:04 UTC, zenatrick commented on src/main/java/seedu/address/model/packinglistitem/UniquePackingList.java
> +    public void setPackingLists(List<Item> items) {
Same as above, `setPackingList` already means multiple items `setPackingLists` means multiple lists which isn't the intention here


**Suggestions:**
Either (preferred since the above method is `setItem()`)
```suggestion
    public void setItems(List<Item> items) {
```

Or
```suggestion
    public void setPackingList(List<Item> items) {
```

2020-03-14 19:04 UTC, zenatrick commented on src/test/java/seedu/address/model/fixedexpense/UniqueFixedExpenseListTest.java
> +    //They have a personBuilder, but since we dont have, improvise by using this for now
Try not to write comments as conversations or note to self. We will be removing them but let's stick close to the textbook best practices.
```suggestion
    // Temporary fields that will be replaced by FixedExpenses made using a FixedExpenseBuilder.
```

2020-03-14 19:04 UTC, zenatrick commented on src/main/java/seedu/address/model/fixedexpense/Description.java
> +    // Spaces does not count.
Not necessary to exclude space since spaces are counted as characters in most apps or editors. May become a problem if the user enters "Train &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;tickets"

Low priority to change, so can leave it as it is. I'm mentioning now in case I forget next time.

2020-03-14 19:04 UTC, zenatrick commented on src/main/java/seedu/address/model/PackingListManager.java
> +        this.packingList.setPackingLists(packingList);
See `line 131` of `UniquePackingList.java`

Either
```suggestion
        this.packingList.setItems(packingList);
```
Or
```suggestion
        this.packingList.setPackingList(packingList);
```

2020-03-15 03:06 UTC, joshlay96 commented on src/main/java/seedu/address/model/fixedexpense/Description.java
> +    // Spaces does not count.
Was thinking of that while doing the testing as someone could just put empty spaces ("  ") as a description, which kinds of make it hard if we are going to manipulate the strings in the future.

2020-03-15 03:09 UTC, joshlay96 commented
Dont think it would work tho, as other methods depend on the function name. Causing the test to fail instead

2020-03-15 03:26 UTC, joshlay96 commented on src/main/java/seedu/address/model/packinglistitem/UniquePackingList.java
> +    public void setPackingLists(UniquePackingList replacement) {
Ill just change it to setPackingList for now. Need to look at cat to see which one she prefers.

2020-03-15 04:37 UTC, zenatrick approved these changes

2020-03-15 05:09 UTC, merged